{% set name = "xeus-zmq" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-zmq/archive/{{ version }}.tar.gz
  sha256: 55ebfca641e2295dbc0d6c85dbfb54810762bc0792d3e464d32f79a5ce0bdd26

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - pkg-config  # [unix]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - nlohmann_json
    - libuuid  # [linux]
    - cppzmq >=4.8.1,<5
    - zeromq
    - openssl <4.0
    - xeus >=5,<6.0
  # zeromq, libuuid and xeus have run_exports sections. No need to add them as
  # run requirements. xeus headers expose headers from nlohmann_json 
  # but does not depend on them at runtime.
  run_constrained:
    - {{ pin_compatible('nlohmann_json', max_pin='x.x.x') }}
    - {{ pin_compatible('cppzmq', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xeus-zmq  # [unix]
    - test -f ${PREFIX}/include/xeus-zmq/xeus-zmq.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-zmq/xeus-zmqConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-zmq/xeus-zmqConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_INC%\\xeus-zmq\\xeus-zmq.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\xeus-zmq\\xeus-zmqConfig.cmake (exit 0)  # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\xeus-zmq\\xeus-zmqConfigVersion.cmake (exit 0)  # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-zmq
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ZeroMQ-based middleware for xeus
  description: ZeroMQ-based middleware for xeus
  doc_url: https://xeus.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xeus-zmq

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - anutosh491
