context:
  version: "4.0.0"
  build_number: 0

package:
  name: xeus-zmq
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-zmq/archive/${{ version }}.tar.gz
  sha256: 6a87c0edeefae1350743071cd78c825d6ab21e771b52610ef7e41c434af20db6

build:
  number: ${{ build_number }}

requirements:
  run_exports:
    - ${{ pin_subpackage('xeus-zmq', upper_bound='x.x') }}
  build:
    - cmake
    - ninja
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - if: unix
      then:
        - pkg-config
  host:
    - nlohmann_json
    - nlohmann_json-abi
    - cppzmq >=4.8.1,<5
    - zeromq
    - openssl <4.0
    - xeus >=6,<7.0
    - if: linux
      then:
        - libuuid
  # zeromq, libuuid and xeus have run_exports sections. No need to add them as
  # run requirements. nlohmann_json-abi has run_exports section to ensure headers
  # of nlohmann_json used at build time will be the same as those used at
  # runtime.

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}include/xeus-zmq/xeus-zmq.hpp
          - ${{ "Library/" if win }}lib/cmake/xeus-zmq/xeus-zmqConfig.cmake
          - ${{ "Library/" if win }}lib/cmake/xeus-zmq/xeus-zmqConfigVersion.cmake

about:
  homepage: https://github.com/jupyter-xeus/xeus-zmq
  repository: https://github.com/jupyter-xeus/xeus-zmq
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ZeroMQ-based middleware for xeus
  description: ZeroMQ-based middleware for xeus
  documentation: https://xeus.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - anutosh491
